### ISSUE TITLE
Text goes out of border

### ISSUE THREAD

**Issue by rEnr3n** [OllieTerrance/Homely#7]
I've set a long text for a link and the text goes out of border. Please make the buttons/borders self-adjust.

**Comment by OllieTerrance** [comment]
Does adding the following to your custom CSS fix it?

```css
#links .btn {
  white-space: normal;
}
```
